### ISSUE TITLE
Norwegian localetypes

### ISSUE THREAD

**Issue by elden1337** [elden1337/peaqev-core#14]
- [x] elden1337/hass-peaq#86 
- [x] elden1337/hass-peaq#87 
- [x] elden1337/hass-peaq#88 
- [x] elden1337/peaqev-core#13
